### ISSUE TITLE
--profile gave technical error if --save is omitted

### ISSUE THREAD

**Issue by ivan-saorin** [Openmacro/openmacro#4]
to replicate:
`py -m openmacro --profile "<your_profile>"` omitting the --save flag.

returns
`py -m openmacro --profile "<your_profile>"
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "<...>\site-packages\openmacro\__main__.py", line 137, in <module>
    main()
  File "<...>\site-packages\openmacro\__main__.py", line 132, in main
    profile = parse_args()
              ^^^^^^^^^^^^
  File "<...>\site-packages\openmacro\__main__.py", line 110, in parse_args
    raise KeyError("Profile does not exist.")`

**Comment by amooo-ooo** [comment]
Fixed in latest patch. Removed `--save`, added flags `--update`, `--versions` and cleaned up implementation on how args are handled. More details in README.md.
