### ISSUE TITLE
Unable to setup openmacro

### ISSUE THREAD

**Issue by a7xr** [Openmacro/openmacro#6]
Can someone help to fix the error below ?

$ macro --api_key "api001"
Traceback (most recent call last):
  File "/path/venv_py3_11/bin/macro", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/path/venv_py3_11/lib/python3.11/site-packages/openmacro/__main__.py", line 133, in main
    macro = Openmacro(profile)
            ^^^^^^^^^^^^^^^^^^
  File "/path/venv_py3_11/lib/python3.11/site-packages/openmacro/core/__init__.py", line 86, in __init__
    self.ltm = self.memory.get_collection("ltm")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/venv_py3_11/lib/python3.11/site-packages/chromadb/api/client.py", line 142, in get_collection
    model = self._server.get_collection(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/venv_py3_11/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 146, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/path/venv_py3_11/lib/python3.11/site-packages/chromadb/api/fastapi.py", line 226, in get_collection
    resp_json = self._make_request(
                ^^^^^^^^^^^^^^^^^^^
  File "/path/venv_py3_11/lib/python3.11/site-packages/chromadb/api/fastapi.py", line 87, in _make_request
    BaseHTTPClient._raise_chroma_error(response)
  File "/path/venv_py3_11/lib/python3.11/site-packages/chromadb/api/base_http_client.py", line 96, in _raise_chroma_error
    raise chroma_error
chromadb.errors.InvalidCollectionException: Collection ltm does not exist.

$ macro --profile profile.py --save
Traceback (most recent call last):
  File "/path/venv_py3_11/bin/macro", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/path/venv_py3_11/lib/python3.11/site-packages/openmacro/__main__.py", line 133, in main
    macro = Openmacro(profile)
            ^^^^^^^^^^^^^^^^^^
  File "/path/venv_py3_11/lib/python3.11/site-packages/openmacro/core/__init__.py", line 86, in __init__
    self.ltm = self.memory.get_collection("ltm")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/venv_py3_11/lib/python3.11/site-packages/chromadb/api/client.py", line 142, in get_collection
    model = self._server.get_collection(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/venv_py3_11/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 146, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/path/venv_py3_11/lib/python3.11/site-packages/chromadb/api/fastapi.py", line 226, in get_collection
    resp_json = self._make_request(
                ^^^^^^^^^^^^^^^^^^^
  File "/path/venv_py3_11/lib/python3.11/site-packages/chromadb/api/fastapi.py", line 87, in _make_request
    BaseHTTPClient._raise_chroma_error(response)
  File "/path/venv_py3_11/lib/python3.11/site-packages/chromadb/api/base_http_client.py", line 96, in _raise_chroma_error
    raise chroma_error
chromadb.errors.InvalidCollectionException: Collection ltm does not exist.

**Comment by amooo-ooo** [comment]
Bug with the long term memory system, should be fixed in the latest build. Install the latest version and try again:
```shell
pip install openmacro==0.2.8
```
Let me know if this works!

**Comment by a7xr** [comment]
Nope, there is new error:

$ macro --api_key "api001"
Traceback (most recent call last):
  File "/path/venv_py3_11/bin/macro", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/path/venv_py3_11/lib/python3.11/site-packages/openmacro/__main__.py", line 124, in main
    macro = Openmacro(profile)
            ^^^^^^^^^^^^^^^^^^
  File "/path/venv_py3_11/lib/python3.11/site-packages/openmacro/core/__init__.py", line 96, in __init__
    self.prompts = load_prompts(self.prompts_dir, 
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/venv_py3_11/lib/python3.11/site-packages/openmacro/utils/__init__.py", line 69, in load_prompts
    for filename in Path(dir).iterdir():
  File "/usr/lib/python3.11/pathlib.py", line 932, in iterdir
    for name in os.listdir(self):
                ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'core/prompts'

**Comment by amooo-ooo** [comment]
I see, try removing the paths section in your profile and update it. Here's an example:
```python
# imports
from openmacro.profile import Profile
from openmacro.extensions import BrowserKwargs

# profile setup
profile: Profile = Profile(
    user = { 
        "name": "Amor", 
        "version": "1.0.0"
    },
    assistant = {
        "name": "Basil",
    },
    extensions = {
        "Browser": BrowserKwargs(headless=False, engine="google"),
    },
    tts = {
      "enabled": True,
      "engine": "SystemEngine",
    }
)
```

New path systems for profile were implemented to allow custom paths for prompts, memory, etc, I'll update the README.md to match, thanks for raising the issue 🙌

**Comment by a7xr** [comment]
Yeah, it works better now.
